spring.datasource.url=jdbc:postgresql://localhost:5432/SchedulingSportPractices
spring.datasource.username=postgres
spring.datasource.password=123456
# spring.datasource.driver-class-name=org.postgresql.Driver
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update

spring.jpa.properties.hibernate.globally_quoted_identifiers=true

# Variáveis para validações de scheduling
practice.maximum-duration = 180
institution.opening-time = 07:00
institution.closing-time = 22:00
